import { useState } from 'react';
import { downloadBlob, svgToPng } from '../lib/image/imageUtils';
import type { LayoutSettings } from '../lib/model/types';
import { strokesToSvg } from '../lib/render/svg';
import { LAYERS } from '../lib/render/types';
import { FONT_LABELS, type FontId } from '../lib/text/strokeFont';
import { IMPERIAL_SCALES, METRIC_SCALES, MM_PER_INCH } from '../lib/units';
import { useSheet } from '../state/sheet';
import { useStore } from '../state/store';
import { useUI } from '../state/ui';

interface Preset {
  group: string;
  id: string;
  label: string;
  w: number;
  h: number;
}

const inch = (w: number, h: number) => ({ w: w * MM_PER_INCH, h: h * MM_PER_INCH });

export const PRESETS: Preset[] = [
  { group: 'Boards (inches)', id: '8x6', label: '8 × 6 in', ...inch(8, 6) },
  { group: 'Boards (inches)', id: '10x8', label: '10 × 8 in', ...inch(10, 8) },
  { group: 'Boards (inches)', id: '11x8.5', label: '11 × 8.5 in (Letter)', ...inch(11, 8.5) },
  { group: 'Boards (inches)', id: '12x8', label: '12 × 8 in', ...inch(12, 8) },
  { group: 'Boards (inches)', id: '14x11', label: '14 × 11 in', ...inch(14, 11) },
  { group: 'Boards (inches)', id: '16x12', label: '16 × 12 in', ...inch(16, 12) },
  { group: 'Boards (inches)', id: '18x12', label: '18 × 12 in', ...inch(18, 12) },
  { group: 'Boards (inches)', id: '20x16', label: '20 × 16 in', ...inch(20, 16) },
  { group: 'Boards (inches)', id: '24x18', label: '24 × 18 in', ...inch(24, 18) },
  { group: 'Metric', id: '300x200', label: '300 × 200 mm', w: 300, h: 200 },
  { group: 'Metric', id: 'a4', label: 'A4 · 297 × 210 mm', w: 297, h: 210 },
  { group: 'Metric', id: 'a3', label: 'A3 · 420 × 297 mm', w: 420, h: 297 },
  { group: 'xTool full work area', id: 'f1', label: 'xTool F1 · 115 × 115 mm', w: 115, h: 115 },
  { group: 'xTool full work area', id: 'f1u', label: 'xTool F1 Ultra · 220 × 220 mm', w: 220, h: 220 },
  { group: 'xTool full work area', id: 'm1', label: 'xTool M1 · 385 × 300 mm', w: 385, h: 300 },
  { group: 'xTool full work area', id: 'd1pro', label: 'xTool D1 Pro · 430 × 390 mm', w: 430, h: 390 },
  { group: 'xTool full work area', id: 's1', label: 'xTool S1 · 498 × 319 mm', w: 498, h: 319 },
  { group: 'xTool full work area', id: 'p2', label: 'xTool P2 / P2S · 600 × 308 mm', w: 600, h: 308 },
];

function slug(s: string) {
  return s.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').toLowerCase();
}

export function ExportPanel() {
  const { project, update } = useStore();
  const { notify } = useUI();
  const sheet = useSheet();
  const L = project.layout;
  const [unit, setUnit] = useState<'in' | 'mm'>(project.layout.scaleSystem === 'metric' ? 'mm' : 'in');
  const [busy, setBusy] = useState(false);
  const setL = (patch: Partial<LayoutSettings>, key?: string) => update((p) => ({ ...p, layout: { ...p.layout, ...patch } }), key ? { mergeKey: key } : undefined);

  const toUnit = (mm: number) => (unit === 'mm' ? Math.round(mm * 10) / 10 : Math.round((mm / MM_PER_INCH) * 100) / 100);
  const fromUnit = (v: number) => (unit === 'mm' ? v : v * MM_PER_INCH);
  const preset = PRESETS.find((p) => (Math.abs(p.w - L.paperWidthMm) < 0.5 && Math.abs(p.h - L.paperHeightMm) < 0.5) || (Math.abs(p.h - L.paperWidthMm) < 0.5 && Math.abs(p.w - L.paperHeightMm) < 0.5));
  const base = slug(project.annotations.projectName || project.property.line1 || 'house') || 'house';
  const title = `${project.annotations.title}${project.property.line1 ? ` — ${project.property.line1}` : ''}`;
  const description = `Scale ${sheet.scale?.label}. Sheet ${Math.round(L.paperWidthMm)} x ${Math.round(L.paperHeightMm)} mm. Generated by Blueprint Engraver.`;

  const downloadSvg = (mode: 'laser' | 'blueprint') => {
    const svg = strokesToSvg(sheet.widthMm, sheet.heightMm, sheet.strokes, { mode, colorMode: L.colorMode, title, description });
    downloadBlob(new Blob([svg], { type: 'image/svg+xml' }), `${base}-front-elevation-${mode}.svg`);
  };
  const downloadPng = async () => {
    setBusy(true);
    try {
      const svg = strokesToSvg(sheet.widthMm, sheet.heightMm, sheet.strokes, { mode: 'blueprint', colorMode: 'layers' });
      const png = await svgToPng(svg, sheet.widthMm, sheet.heightMm);
      downloadBlob(png, `${base}-front-elevation.png`);
    } catch (e) {
      notify(`PNG export failed: ${(e as Error).message}`, 'error');
    } finally {
      setBusy(false);
    }
  };

  const groups = [...new Set(PRESETS.map((p) => p.group))];
  const lengthM = sheet.stats.lengthMm / 1000;

  return (
    <div className="panel">
      <section>
        <h2>Board size</h2>
        <label>
          Preset
          <select
            value={preset?.id ?? 'custom'}
            onChange={(e) => {
              const p = PRESETS.find((x) => x.id === e.target.value);
              if (p) {
                const landscape = L.paperWidthMm >= L.paperHeightMm;
                const [w, h] = landscape ? [Math.max(p.w, p.h), Math.min(p.w, p.h)] : [Math.min(p.w, p.h), Math.max(p.w, p.h)];
                setL({ paperWidthMm: w, paperHeightMm: h });
              }
            }}
          >
            <option value="custom">Custom</option>
            {groups.map((g) => (
              <optgroup key={g} label={g}>
                {PRESETS.filter((p) => p.group === g).map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.label}
                  </option>
                ))}
              </optgroup>
            ))}
          </select>
        </label>
        <div className="grid3">
          <label>
            Width
            <input type="number" step="any" min={1} value={toUnit(L.paperWidthMm)} onChange={(e) => setL({ paperWidthMm: Math.max(40, fromUnit(Number(e.target.value) || 0)) }, 'pw')} />
          </label>
          <label>
            Height
            <input type="number" step="any" min={1} value={toUnit(L.paperHeightMm)} onChange={(e) => setL({ paperHeightMm: Math.max(40, fromUnit(Number(e.target.value) || 0)) }, 'ph')} />
          </label>
          <label>
            Units
            <select value={unit} onChange={(e) => setUnit(e.target.value as 'in' | 'mm')}>
              <option value="in">in</option>
              <option value="mm">mm</option>
            </select>
          </label>
        </div>
        <div className="row wrap">
          <button className="btn small" onClick={() => setL({ paperWidthMm: L.paperHeightMm, paperHeightMm: L.paperWidthMm })}>
            ⟲ Rotate
          </button>
          <label className="inline">
            Margin
            <input type="number" min={0} max={40} step={0.5} value={L.marginMm} onChange={(e) => setL({ marginMm: Math.max(0, Number(e.target.value) || 0) }, 'margin')} /> mm
          </label>
        </div>
      </section>

      <section>
        <h2>Drawing scale</h2>
        <label>
          Scale
          <select value={L.scaleId} onChange={(e) => setL({ scaleId: e.target.value })}>
            <option value="auto">Auto — largest standard scale that fits</option>
            <option value="fit">Fill the board (non-standard ratio)</option>
            <optgroup label="Architectural (imperial)">
              {IMPERIAL_SCALES.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.label}
                </option>
              ))}
            </optgroup>
            <optgroup label="Metric">
              {METRIC_SCALES.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.label}
                </option>
              ))}
            </optgroup>
          </select>
        </label>
        {L.scaleId === 'auto' && (
          <div className="seg">
            <button className={L.scaleSystem === 'imperial' ? 'on' : ''} onClick={() => setL({ scaleSystem: 'imperial' })}>
              Imperial scales
            </button>
            <button className={L.scaleSystem === 'metric' ? 'on' : ''} onClick={() => setL({ scaleSystem: 'metric' })}>
              Metric scales
            </button>
          </div>
        )}
        <p className="muted small">
          Using <b>{sheet.scale?.label}</b> — 1 ft on the house = {sheet.mmPerFt.toFixed(2)} mm on the board. The scale note and bar on the sheet are exact
          at this board size.
        </p>
      </section>

      <section>
        <h2>Lettering & lines</h2>
        <label>
          Font (single-line, laser friendly)
          <select value={L.font} onChange={(e) => setL({ font: e.target.value as FontId })}>
            {(Object.keys(FONT_LABELS) as FontId[]).map((f) => (
              <option key={f} value={f}>
                {FONT_LABELS[f]}
              </option>
            ))}
          </select>
        </label>
        <label className="range">
          Text size ×{L.textScale.toFixed(2)}
          <input type="range" min={0.6} max={1.8} step={0.05} value={L.textScale} onChange={(e) => setL({ textScale: parseFloat(e.target.value) }, 'textScale')} />
        </label>
        <div className="grid2">
          <label>
            Detail
            <select value={L.detail} onChange={(e) => setL({ detail: e.target.value as LayoutSettings['detail'] })}>
              <option value="low">Low (fewer lines)</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
            </select>
          </label>
          <label title="Parallel hatch lines closer than this are thinned out so they don't burn together">
            Min line gap (mm)
            <input type="number" min={0.3} max={3} step={0.1} value={L.minHatchMm} onChange={(e) => setL({ minHatchMm: Math.max(0.3, Number(e.target.value) || 0.9) }, 'minHatch')} />
          </label>
        </div>
        <div className="grid2">
          <label>
            Frame
            <select value={L.frame} onChange={(e) => setL({ frame: e.target.value as LayoutSettings['frame'] })}>
              <option value="none">None</option>
              <option value="single">Single line</option>
              <option value="double">Double line</option>
            </select>
          </label>
          <label>
            Cut line
            <select value={L.cutOutline} onChange={(e) => setL({ cutOutline: e.target.value as LayoutSettings['cutOutline'] })}>
              <option value="none">None</option>
              <option value="rect">Rectangle</option>
              <option value="rounded">Rounded corners</option>
            </select>
          </label>
        </div>
        {L.cutOutline === 'rounded' && (
          <label className="inline">
            Corner radius
            <input type="number" min={0} max={60} value={L.cornerRadiusMm} onChange={(e) => setL({ cornerRadiusMm: Math.max(0, Number(e.target.value) || 0) }, 'radius')} /> mm
          </label>
        )}
        <label>
          Laser colours
          <select value={L.colorMode} onChange={(e) => setL({ colorMode: e.target.value as LayoutSettings['colorMode'] })}>
            <option value="layers">One colour per line weight (set power per colour)</option>
            <option value="single">Everything black (one pass)</option>
          </select>
        </label>
        {L.colorMode === 'layers' && (
          <ul className="legend">
            {LAYERS.filter((l) => sheet.stats.byLayer[l.id].polylines > 0).map((l) => (
              <li key={l.id}>
                <span className="swatch" style={{ background: l.color }} />
                <b>{l.name}</b> <span className="muted">— {l.description}</span>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section>
        <h2>Download</h2>
        <button className="btn primary wide" onClick={() => downloadSvg('laser')} disabled={!project.elements.length}>
          ⬇ Laser SVG for xTool
        </button>
        <div className="row">
          <button className="btn grow" onClick={() => downloadSvg('blueprint')} disabled={!project.elements.length}>
            Blueprint SVG
          </button>
          <button className="btn grow" onClick={downloadPng} disabled={busy || !project.elements.length}>
            {busy ? 'Rendering…' : 'PNG proof (300 dpi)'}
          </button>
        </div>
        <p className="muted small">
          {sheet.stats.polylines.toLocaleString()} paths · {lengthM.toFixed(1)} m of line (about {Math.max(1, Math.round(sheet.stats.lengthMm / 100 / 60))} min of
          scoring at 100 mm/s). Overlapping lines are merged so nothing burns twice.
        </p>
      </section>

      <section className="tips">
        <h3>Engraving on an xTool</h3>
        <ol>
          <li>In xTool Creative Space, import the laser SVG. It keeps its real size ({Math.round(L.paperWidthMm)} × {Math.round(L.paperHeightMm)} mm).</li>
          <li>Set the drawing to <b>Score</b> (line engraving). Lettering uses single-stroke fonts, so it scores cleanly as one line per stroke.</li>
          <li>With colour layers, give outlines more power than hatching for real line weights; or pick “Everything black” for one setting.</li>
          <li>The red cut line (if enabled) is for cutting the plaque out — set it to <b>Cut</b> or delete it.</li>
          <li>Always run a small test on scrap material first.</li>
        </ol>
      </section>
    </div>
  );
}
